export const sliderItems = [
  {
    id: 1,
    img: "images/slider1.jpg",
    title: "Summer Sale",
    desc: " Don't Compromise on Homes, Get 30% Off on New Home Appliances",
    bg: "fdf0f4",
  },
  {
    id: 2,
    img: "images/slider2.jpg",
    title: "Popular Sale",
    desc: " Don't Compromise on Homes, Get 30% Off on New Home Appliances",
    bg: "ffc8c1",
  },
  {
    id: 3,
    img: "images/slider3.jfif",
    title: "Winter Sale",
    desc: " Don't Compromise on Homes, Get 30% Off on New Home Appliances",
    bg: "bad4ff",
  },
];

export const popularProducts = [
  {
    id: 1,
    img: "images/white (1).jfif",
    name: "White shirt",
    color: "White",
    price: 2345,
    quantity: 8,
    size: "XS",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 2,
    img: "images/white-2.jfif",
    name: "White Maxi",
    color: "White",
    price: 6780,
    quantity: 3,
    size: "L",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 3,
    img: "images/white (3).jfif",
    name: "White Long shirt",
    color: "White",
    price: 4560,
    quantity: 7,
    size: "S",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 4,
    img: "images/black (1).jfif",
    name: " Black Shirt",
    color: "Black",
    price: 1890,
    quantity: 2,
    size: "XS",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 5,
    img: "images/black (2).jfif",
    name: "Black Long shirt",
    color: "Black",
    price: 459,
    quantity: 5,
    size: "M",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 6,
    img: "images/black (3).jfif",
    name: "Black  Short Shirt",
    color: "Black",
    price: 1245,
    quantity: 4,
    size: "XL",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 7,
    img: "images/red (2).jfif",
    name: "Red Long Maxi",
    color: "Red",
    price: 567,
    quantity: 2,
    size: "L",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 8,
    img: "images/red.jfif",
    name: "Red frock",
    color: "Red",
    price: 456,
    quantity: 6,
    size: "XL",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 9,
    img: "images/summer2.jfif",
    name: "Red shirt",
    color: "Red",
    price: 600,
    quantity: 3,
    size: "M",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 10,
    img: "images/summer1.jfif",
    name: "Red shirt",
    color: "Yellow",
    price: 600,
    quantity: 6,
    size: "M",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 11,
    img: "images/popular8.jfif",
    name: "Red shirt",
    color: "Yellow",
    price: 600,
    quantity: 3,
    size: "M",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 12,
    img: "images/popular7.jfif",
    name: "Red shirt",
    color: "Yellow",
    price: 600,
    quantity: 6,
    size: "M",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 13,
    img: "images/popular6.jfif",
    name: "Red shirt",
    color: "Green",
    price: 600,
    quantity: 4,
    size: "M",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 14,
    img: "images/popular5.jfif",
    name: "Red shirt",
    color: "Green",
    price: 600,
    quantity: 7,
    size: "M",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 15,
    img: "images/popular4.jfif",
    name: "Red shirt",
    color: "Green",
    price: 600,
    quantity: 1,
    size: "M",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 16,
    img: "images/popular3.jfif",
    name: "Red shirt",
    color: "Blue",
    price: 600,
    quantity: 4,
    size: "M",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 17,
    img: "images/popular2.jfif",
    name: "Red shirt",
    color: "Blue",
    price: 600,
    quantity: 5,
    size: "M",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 18,
    img: "images/popular1.jfif",
    name: "Red shirt",
    color: "Blue",
    price: 600,
    quantity: 5,
    size: "M",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
];
export const categories = [
  {
    id: 1,
    img: "images/summer1.jfif",
    title: "SHIRT STYLE",
  },
  {
    id: 2,
    img: "images/summer2.jfif",
    title: "LOSE STYLE",
  },
  {
    id: 3,
    img: "images/summer3.jfif",
    title: "Summer STYLE",
  },
];
export const UserLogin = [
  {
    id: 7,
    name: "Aqsa",
    email: "aqsa@gmail.com",
    role: "admin",
    img: "images/Aqsa.jfif",
    num: 12345678901,
  },
  {
    id: 1,
    name: "Hira",
    email: "hira@gmail.com",
    role: "user",
    img: "images/hira.webp",
    num: 12345678901,
  },
  {
    id: 2,
    name: "Ayesha",
    email: "ayesha@gmail.com",
    role: "user",
    img: "images/dummy1.jpg",
    num: 12345678901,
  },
  {
    id: 3,
    name: "Gul",
    email: "gul@gmail.com",
    role: "user",
    img: "images/user3.webp",
    num: 12345678901,
  },
  {
    id: 4,
    name: "Habiba",
    email: "habiba@gmail.com",
    role: "user",
    img: "images/user4.jfif",
    num: 12345678901,
  },
  {
    id: 5,
    name: "Azka",
    email: "azka@gmail.com",
    role: "user",
    img: "images/user6.jfif",
    num: 12345678901,
  },
  {
    id: 6,
    name: "Rani",
    email: "ranih@gmail.com",
    role: "user",
    img: "images/zarish.webp",
    num: 12345678901,
  },
  {
    id: 7,
    name: "Zarish",
    email: "zarish@gmail.com",
    role: "admin",
    img: "images/zarish.webp",
    num: 12345678901,
  },
];
