export const sliderItems = [
  {
    id: 1,
    img: "images/slider1.jpg",
    title: "Summer Sale",
    desc: " Don't Compromise on Homes, Get 30% Off on New Home Appliances",
    bg: "fdf0f4",
  },
  {
    id: 2,
    img: "images/slider2.jpg",
    title: "Popular Sale",
    desc: " Don't Compromise on Homes, Get 30% Off on New Home Appliances",
    bg: "ffc8c1",
  },
  {
    id: 3,
    img: "images/slider3.jfif",
    title: "Winter Sale",
    desc: " Don't Compromise on Homes, Get 30% Off on New Home Appliances",
    bg: "bad4ff",
  },
];

export const popularProducts = [
  {
    id: 1,
    img: "images/white (1).jfif",
    name: "White shirt",
    color: "White",
    price: 2345,
    quantity: 1,
    size: "XS",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 2,
    img: "images/white (2).jfif",
    name: "White Maxi",
    color: "White",
    price: 6780,
    quantity: 1,
    size: "L",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 3,
    img: "images/white (3).jfif",
    name: "White Long shirt",
    color: "White",
    price: 4560,
    quantity: 1,
    size: "S",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 4,
    img: "images/black (1).jfif",
    name: " Black Frock",
    color: "Black",
    price: 1890,
    quantity: 1,
    size: "XS",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 5,
    img: "images/black (2).jfif",
    name: "Black Long shirt",
    color: "Black",
    price: 459,
    quantity: 1,
    size: "M",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 6,
    img: "images/black (3).jfif",
    name: "Black shirt",
    color: "Black",
    price: 1245,
    quantity: 1,
    size: "XL",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 7,
    img: "images/red (2).jfif",
    name: "Red Long Maxi",
    color: "Red",
    price: 567,
    quantity: 1,
    size: "L",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 8,
    img: "images/red (3).jfif",
    name: "Red frock",
    color: "Red",
    price: 456,
    quantity: 1,
    size: "XL",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
  {
    id: 9,
    img: "images/red.jfif",
    name: "Red shirt",
    color: "Red",
    price: 600,
    quantity: 1,
    size: "M",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo eos quidem laboriosam?",
  },
];
export const categories = [
  {
    id: 1,
    img: "images/summer1.jfif",
    title: "SHIRT STYLE",
  },
  {
    id: 2,
    img: "images/summer2.jfif",
    title: "LOSE STYLE",
  },
  {
    id: 3,
    img: "images/summer3.jfif",
    title: "Summer STYLE",
  },
];
export const UserLogin = [
  {
    id: 1,
    name: "Aqsa",
    email: "aqsa@gmail.com",
    role: "admin",
  },
  {
    id: 2,
    name: "Hira",
    email: "hira@gmail.com",
    role: "user",
  },
  {
    id: 3,
    name: "Ayesha",
    email: "ayesha@gmail.com",
    role: "user",
  },
  {
    id: 4,
    name: "Gul",
    email: "gul@gmail.com",
    role: "user",
  },
  {
    id: 5,
    name: "Habiba",
    email: "habiba@gmail.com",
    role: "user",
  },
  {
    id: 6,
    name: "Azka",
    email: "azka@gmail.com",
    role: "user",
  },
  {
    id: 7,
    name: "Zarish",
    email: "zarish@gmail.com",
    role: "admin",
  },
];
